# Notes

## Required packages

First, [see the mean.io README](https://github.com/linnovate/meanio#basic-usage),
and install according to the directions there.

## Contrib packages

The contrib packages are excluded intentionally in the `.gitignore`, because
these were generated by running the following commands:

* `mean init <app-name>` where app name would be something like the
  the directory named "basic-example."
